version: '3.8'

services:
  golang-ture:
    build: ./
    command: ./wait-for-postgres.sh db ./golang-ture
    ports:
      - 8787:8787
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty

  db:
    restart: always
    image: postgres:latest
    volumes:
    - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5436:5432