// Code generated by "stringer -type=TodoItemStatus"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Backlog-0]
	_ = x[InProgress-1]
	_ = x[Review-2]
	_ = x[Done-3]
}

const _TodoItemStatus_name = "BacklogInProgressReviewDone"

var _TodoItemStatus_index = [...]uint8{0, 7, 17, 23, 27}

func (i TodoItemStatus) String() string {
	if i < 0 || i >= TodoItemStatus(len(_TodoItemStatus_index)-1) {
		return "TodoItemStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TodoItemStatus_name[_TodoItemStatus_index[i]:_TodoItemStatus_index[i+1]]
}
