package main

import (
	"fmt"
	"go/types"
	"os"
	"path/filepath"
	"strings"

	. "github.com/dave/jennifer/jen"
	"golang.org/x/tools/go/packages"
)

func main() {
	// Handle arguments to command
	if len(os.Args) != 2 {
		failErr(fmt.Errorf("expected exactly one argument: <source type>"))
	}
	sourceType := os.Args[1]
	sourceTypePackage, sourceTypeName := splitSourceType(sourceType)

	// Inspect package and use type checker to infer imported types
	pkg := loadPackage(sourceTypePackage)

	// Lookup the given source type name in the package declarations
	obj := pkg.Types.Scope().Lookup(sourceTypeName)
	if obj == nil {
		failErr(fmt.Errorf("%s not found in declared types of %s",
			sourceTypeName, pkg))
	}

	// We check if it is a declared type
	if _, ok := obj.(*types.TypeName); !ok {
		failErr(fmt.Errorf("%v is not a named type", obj))
	}
	// We expect the underlying type to be a struct
	structType, ok := obj.Type().Underlying().(*types.Struct)
	if !ok {
		failErr(fmt.Errorf("type %v is not a struct", obj))
	}

	// Generate code using jennifer
	err := generate(sourceTypeName, structType)
	if err != nil {
		failErr(err)
	}
}

func generate(sourceTypeName string, structType *types.Struct) error {
	goPackage := os.Getenv("GOPACKAGE")

	f := NewFile(goPackage)

	f.PackageComment("Code generated by generator, DO NOT EDIT.")

	for i := 0; i < structType.NumFields(); i++ {
		field := structType.Field(i)

		switch v := field.Type().(type) {
		case *types.Basic:
			f.Func().Params(
				Id("t").Op("*").Id(sourceTypeName),
			).Id("Get" + field.Name()).Params().Id(v.String()).Block(
				Return(Id("t").Dot(field.Name())),
			).Line().Line().Func().Params(
				Id("t").Op("*").Id(sourceTypeName),
			).Id("Set" + field.Name()).Params(Id("new" + field.Name()).Id(v.String())).Block(
				Id("t").Dot(field.Name()).Op("=").Id("new" + field.Name()),
			).Line().Line()
		case *types.Named:
			typeName := v.Obj()
			f.Func().Params(
				Id("t").Op("*").Id(sourceTypeName),
			).Id("Get"+field.Name()).Params().Qual(
				typeName.Pkg().Path(),
				typeName.Name()).Block(
				Return(Id("t").Dot(field.Name())),
			).Line().Func().Params(
				Id("t").Op("*").Id(sourceTypeName),
			).Id("Set" + field.Name()).Params(Id("new"+field.Name()).Qual(
				typeName.Pkg().Path(),
				typeName.Name())).Block(
				Id("t").Dot(field.Name()).Op("=").Id("new" + field.Name()),
			)
		default:
			return fmt.Errorf("struct field type not hanled: %T", v)
		}
	}

	goFile := os.Getenv("GOFILE")
	ext := filepath.Ext(goFile)
	baseFilename := goFile[0 : len(goFile)-len(ext)]
	targetFilename := baseFilename + "_" + strings.ToLower(sourceTypeName) + "_gen.go"

	return f.Save(targetFilename)
}

func loadPackage(path string) *packages.Package {
	cfg := &packages.Config{Mode: packages.NeedTypes | packages.NeedImports}
	pkgs, err := packages.Load(cfg, path)
	if err != nil {
		failErr(fmt.Errorf("loading packages for inspection: %v", err))
	}
	if packages.PrintErrors(pkgs) > 0 {
		os.Exit(1)
	}

	return pkgs[0]
}

func splitSourceType(sourceType string) (string, string) {
	idx := strings.LastIndexByte(sourceType, '.')
	if idx == -1 {
		failErr(fmt.Errorf(`expected qualified type as "pkg/path.MyType"`))
	}
	sourceTypePackage := sourceType[0:idx]
	sourceTypeName := sourceType[idx+1:]
	return sourceTypePackage, sourceTypeName
}

func failErr(err error) {
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}
